name: Test and Deploy My App

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]

jobs:
  laravel-tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
 
    - name: Install Dependencies
      run: composer install

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Clear application cache
      run: php artisan config:clear && php artisan cache:clear
 

  build: 
    name: Build Application

    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push Docker Image 
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: anis3139/multipurpose-admin-panel-boilerplate
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
 
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
